project:
  type: book
  output-dir: docs

book:
  title: "Applied Population Genetics"
  author: "Rodney J. Dyer"
  date: "1/6/2026"
  cover-image: "media/TitlePage_small.png"
  repo-url: "https://github.com/dyerlab/applied_population_genetics"
  chapters:
    - index.qmd
    - Introduction.qmd
    - part: R_Ecosystem.qmd
      chapters:
        - R.qmd
        - Positron.qmd
        - Markdown.qmd
        - DataTypes.qmd
        - DataContainers.qmd
        - FactorData.qmd
        - Tidyverse.qmd
        - TabularData.qmd
        - Graphics.qmd
        - Functions.qmd
        - Publishing.qmd
    - part: Backmatter.qmd
      chapters:
      - Summary.qmd
      - References.qmd
  appendices: 
    - DataSets.qmd
    - BloomSpread.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    toc-depth: 2 
    respect-user-color-scheme: true
    css:
      - styles/captions.css
    theme:
      - cosmo
      - brand

execute:
  warning: false
  message: false
  error: false
  freeze: auto  # set to false for release 
  eache: true   # set to false for release


